#spring.application.name=ecom-application

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.jpa.show-sql=true #enable logging of sql in console

#for test purpose for prod use update #automaticalyy create database table based on your entity classes
#spring.jpa.hibernate.ddl-auto=create

spring:
  application:
    name: ecom-application
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
